name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ stable, beta, dev ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == 'stable' }}
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test

  validate_analyzer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ stable ]
        analyzer:
          - ^2.0.0
          - ^3.0.0
          - ^4.0.0
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Update analyzer constraint to ${{ matrix.analyzer }}
        run: dart pub remove analyzer && dart pub add analyzer:${{ matrix.analyzer }} && git diff pubspec.yaml
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
